import tables

let opnames = {
    HLT: "HLT",
    JMP: "JMP",
    CAL: "CAL",
    RET: "RET",
    JZ: "JZ",
    JNZ: "JNZ",
    LIT: "LIT",
    MOV: "MOV",
    ADD: "ADD",
    SUB: "SUB",
    MOD: "MOD",
    MUL: "MUL",
    DIV: "DIV",
    NEG: "NEG",
    PUT: "PUT",
    GET: "GET",
    PUTC: "PUTC",
    GETC: "GETC",
    EOF: "EOF",
    CMP: "CMP",
    JEQ: "JEQ",
    JGT: "JGT",
    JLT: "JLT",
    JNE: "JNE",
    JGE: "JGE",
    JLE: "JLE",
    LDAP: "LDAP",
    STAP: "STAP",
    LDA:  "LDA",
    STA:  "STA",
}.to_table
